name: CI Checks
permissions:
  contents: read

## This workflow runs when any of the following occur:
## * A push is made to the main branch
## * A pull request is created or updated in the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  ## This builds the application and runs CI checks
  ## A matrix stategy is used to allow for future python versions
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      ## https://github.com/actions/checkout
      - uses: actions/checkout@v5

      ## https://github.com/actions/setup-python
      ## https://github.com/actions/python-versions
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install application dependencies
        run: make install

      - name: Lint application files
        run: make lint

      - name: Format application files
        run: make format

      - name: Test application functionality
        run: make test

      - name: Dependency check for known vulnerabilities
        run: make depcheck
        env:
          ## https://ossindex.sonatype.org/
          ## https://github.com/sonatype-nexus-community/ossindex-python/blob/main/docs/usage.rst#authenticating-to-oss-index
          OSS_INDEX_USER: ${{ secrets.OSS_INDEX_USER }}
          OSS_INDEX_PASSWORD: ${{ secrets.OSS_INDEX_PASSWORD }}
          OSS_INDEX_API_TOKEN: ${{ secrets.OSS_INDEX_API_TOKEN }}

      - name: Run a source code security analyzer
        run: make secscan
